base_url = "https://romac.github.io/corophage"
title = "corophage"
description = "An effect handler library for stable Rust"
compile_sass = true
minify_html = false
build_search_index = true

[search]
include_title = true
include_description = true
include_content = true

[markdown.highlighting]
enabled = true
theme = "catppuccin-mocha"

[extra]
repo_url = "https://github.com/romac/corophage"
crates_url = "https://crates.io/crates/corophage"
docs_rs_url = "https://docs.rs/corophage"
